# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge. 

You need to use to format strings. 

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius. 
```

In [3]:
# complete your program here
c = input ('Please input the temperature in Celsius ')

c = float(c)

f = 9/5 * c + 32

print(f'{c}C is {f} in Fahrenheit')

Please input the temperature in Celsius 50
50.0C is 122.0 in Fahrenheit


In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Tim
Welcome, Tim!


In [2]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

#print(f)
f = float(f)
#print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 50
50.0F is 10.0 in Celsius. 
50.0F is 10.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit. 
```

Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [4]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
d=float(d)
if m == 'C':
    c= (9/5*d)+32
    print(f'{d}C is {c} in Celsius')
if m == 'F':
    f = (d-32)*5/9
    print(f'{d}F is {f} in Fahrenheit')
else:
    print('Please enter valid temperature type')

Please enter the temperature: 50
Is this in Celsius or Fahrenheit? F
50.0F is 10.0 in Fahrenheit


## Question 2

Have some fun with strings.

In [5]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [6]:
# Find the length of this sentence.
len(sentence)

48

In [7]:
# Convert the whole string to lower case. 
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [8]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9:37])

heap. Show me the code - Lin


In [9]:
# Split the sentence into a list of substrings by space ' '. 
list=sentence.split()
print(list)

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [10]:
# Given the sentence, output a list of words in lowercase (without punctuations). 
sentence=sentence.lower()
list=sentence.split()
list[2]='cheap'
list.remove('-')

print(list)

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [11]:
# Count the total number of vowels in the sentence.

vowels = ['a','e','i','o','u']

count= 0
for char in sentence:
    if char in vowels:
        count += 1

print(count)



13


In [12]:
# Find the positions (indexes) of all vowels in the sentence. 
for i in range(len(sentence)):
    
    if sentence[i] in vowels:
        print(i)
    

1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [13]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]

cubes=[]
for i in range(5):
    cubes.append(i*i*i)
print(cubes)



[0, 1, 8, 27, 64]


In [14]:
# Use list comprehension to create the same list
cubes = [i*i*i for i in range(5)]
cubes


[0, 1, 8, 27, 64]

In [15]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"

vowels = [i for i in range(len(sentence.lower())) if sentence[i] in 'aeiou']
vowels

[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]

In [16]:

# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...] 
fibonacci = []
n = input('How many numbers do you want? ')
# add your code here
n = int(n)

if n == 1:
    fibonacci = [0]
elif n == 2:
    fibonacci = [0, 1]
else: 
    fibonacci = [0, 1]
    for i in range(2, n):
       
        fibonacci.append(fibonacci[i-1]+fibonacci[i-2])
        
fibonacci


How many numbers do you want? 10


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [17]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer': .95,'Moderna': .95, 'AstraZeneaca': .72 , 'Johnson & Johnson': .66}

In [18]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Moderna
0.95


In [19]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary

v_dict.update({'Sputnik V': .914})
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneaca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914}

In [20]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict.update({'Sinovac': .5038})

In [21]:
# Print vaccines with efficacy lower than 90%.
for i in v_dict:
    if v_dict[i] < .90:
        print(v_dict[i])

0.72
0.66
0.5038


In [22]:
# delete the Sinovac vaccine from the dictionary. 
del v_dict['Sinovac']


In [23]:
#Count the occurrence of each alphabet (no space ' ') in this sentence. 
sentence = 'the quick brown fox jumps over the lazy dog'
alpha="abcdefghijklmnopqrstuvwxyz"

# Save the result in a dictionary 
ch_dict = {} 
# Use a loop to iterate all characters
# add your code here
for i in alpha:
    count=0
    for char in sentence:
        if char==i:
            count += 1
    ch_dict.update({i:count})

print(count)
# print the dictionary
print(ch_dict)

1
{'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 3, 'f': 1, 'g': 1, 'h': 2, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 2, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [24]:
import numpy as np

In [25]:
# create a 1-D array of first 20 positive even numbers (starting with 2)

d= np.array([2*i for i in range(1,21) ])
d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [26]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
d= np.array([2*i-1 for i in range(1,21) ])
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [27]:
# create a 10x10 array in the following format: 
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
row=[i for i in range(0,100)]
r1=row[0:10]
r2=row[10:20]
r3=row[20:30]
r4=row[30:40]
r5=row[40:50]
r6=row[50:60]
r7=row[60:70]
r8=row[70:80]
r9=row[80:90]
r10=row[90:100]
ls=[[r1],[r2],[r3],[r4],[r5],[r6],[r7],[r8],[r9],[r10]]

array=np.array(ls)
array


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [28]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0,1,(10,10))
M.shape
M

array([[-6.78685602e-01, -1.21985902e+00,  4.49574903e-01,
         7.93252790e-01, -2.66241623e+00, -9.38503853e-01,
         8.28062670e-01,  1.46275432e-01,  2.37419703e+00,
         2.72153393e-01],
       [-9.69751401e-01,  1.06833907e+00, -9.40050989e-04,
         1.21817838e+00, -1.51238773e+00,  8.87380227e-01,
        -9.92196621e-01, -1.34883667e-01, -3.24802841e-02,
         2.40416764e-01],
       [ 1.25351923e+00, -3.16359189e-01, -1.37634002e+00,
         1.73938473e+00, -2.59710630e-01,  3.72241725e-01,
         1.13900505e+00,  7.43615442e-01,  9.06275822e-01,
         2.78426871e-01],
       [ 3.01250238e+00, -6.30633817e-02, -3.14950936e-01,
         7.04472007e-01, -1.05222847e+00, -1.79215123e-01,
         2.01088219e+00,  6.79837261e-01,  1.19778391e+00,
        -1.55847459e+00],
       [ 2.11087719e-01, -3.73577344e-01,  6.80223929e-01,
         2.06568636e+00,  3.54058177e-01,  6.59630984e-01,
        -2.23034523e-01,  1.13350365e+00,  3.92028423e-02,
         3.

In [29]:
# Count the numbers in M with an absolute value greater than 1.
count=0
for x in M:
    for y in x:
        if abs(y) > 1:
            count += 1
count

32

In [30]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('Column count: ')
r=int(r)
c=int(c)
# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10,20,(r,c))
arr

Row count: 5
Column count: 5


array([[15, 19, 11, 19, 11],
       [10, 12, 18, 18, 13],
       [16, 10, 18, 13, 13],
       [19, 15, 18, 18, 16],
       [16, 19, 11, 13, 17]])

In [31]:
# output the element in the first row and the third column
print(arr[0,2])

11


In [32]:
# output the element in the second row and the last column
arr[1,c-1]

13

In [33]:
# output the second row of the array
arr[1,:]

array([10, 12, 18, 18, 13])

In [34]:
# output the second last row of the array
arr[r-2,:]

array([19, 15, 18, 18, 16])

In [35]:
# output the second column of the array
arr[:,1]

array([19, 12, 10, 15, 19])

In [36]:
# output the second last column of the array
arr[:,c-2]

array([19, 18, 13, 18, 13])

In [37]:
# output the upper-left 3x3 sub-array

arr[0:3,0:3]

array([[15, 19, 11],
       [10, 12, 18],
       [16, 10, 18]])

In [38]:
# output the bottom-left 3x3 sub-array
arr[2:5,2:5]

array([[18, 13, 13],
       [18, 18, 16],
       [11, 13, 17]])

In [39]:
# output the upper-right 3x3 sub-array
arr[0:3,2:5]

array([[11, 19, 11],
       [18, 18, 13],
       [18, 13, 13]])

In [40]:
# output the bottom-right 3x3 sub-array
arr[2:5,0:3]

array([[16, 10, 18],
       [19, 15, 18],
       [16, 19, 11]])

In [41]:
# Create a 1-D array from 1 to 50 (inclusive)
A=[i for i in range(1,51)]
A=np.array(A)
A=A.reshape(5,10)
A
# Reshape A to a 5x10 array in the following format: 
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [1]:
# add a row [51,...,60] to A
B=[i for i in range(51,61)]
B=np.array(B)
B=B.reshape(1,10)
B

A=np.concatenate([A,B],axis=0)
A

NameError: name 'np' is not defined

In [43]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
np.split(A,2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])]

In [44]:
# Add 10 to each element of A
np.add(A,10)

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [45]:
# Calculate the square root of each element in A
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669]])

In [46]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [48]:
# Print the mean, standard devietion of all numbers in M
print(A.mean())
print(A.std())

30.5
17.318102282486574


In [53]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(A.max())
print(np.percentile(A,75))
print(np.median(A))
print(np.percentile(A,25))
print(A.min())

60
45.25
30.5
15.75
1
